#!/usr/bin/env python3
"""gen_mcp.py — Generate MCP configs for the 3 runtimes from harness/manifest.json.

Outputs:
  .mcp.json                          (Claude Code, project scope — written in repo)
  harness/out/codex-mcp.toml         (snippet to merge into ~/.codex/config.toml)
  harness/out/antigravity-mcp.json   (snippet to merge into ~/.gemini/config/mcp_config.json)

--apply-user merges the snippets into the user-scope configs WITH timestamped
backup (key-merge: only our server keys touched). Secret scan aborts any write
containing token-like literals. No secrets ever in generated files — auth via
external files/CLI login or scripts/with-secrets.sh wrapper.
"""
import argparse
import datetime
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = json.loads((ROOT / "harness/manifest.json").read_text(encoding="utf-8"))
OUT = ROOT / "harness" / "out"

SECRET_PAT = re.compile(r"(sk-[A-Za-z0-9]{20,}|AIza[0-9A-Za-z_-]{30,}|ya29\.[0-9A-Za-z_-]+|ghp_[A-Za-z0-9]{30,}|xox[bp]-)")


def scan(text: str, label: str) -> None:
    if SECRET_PAT.search(text):
        print(f"ABORT: secret-like literal detected in {label}", file=sys.stderr)
        sys.exit(1)


def server_for_runtime(name, spec, runtime):
    if runtime not in spec.get("runtimes", []):
        return None
    s = spec
    if runtime == "codex" and spec.get("codexVariant") and spec.get("transport") == "http":
        s = {**spec, **spec["codexVariant"]}
    if s.get("transport") == "http":
        return {"type": "http", "url": s["url"]}
    entry = {"command": s["command"]}
    if s.get("args"):
        entry["args"] = s["args"]
    return entry


def gen_claude() -> str:
    servers = {}
    for name, spec in MANIFEST["mcpServers"].items():
        e = server_for_runtime(name, spec, "claude-code")
        if e:
            servers[name] = e
    return json.dumps({"mcpServers": servers}, indent=2) + "\n"


def gen_codex() -> str:
    lines = ["# Generated by gen_mcp.py — merge into ~/.codex/config.toml"]
    for name, spec in MANIFEST["mcpServers"].items():
        e = server_for_runtime(name, spec, "codex")
        if not e:
            continue
        if e.get("type") == "http":
            lines.append(f'# {name}: HTTP MCP — Codex support experimental; prefer stdio proxy variant')
            continue
        lines.append(f"[mcp_servers.{name}]")
        lines.append(f'command = "{e["command"]}"')
        if e.get("args"):
            lines.append("args = [" + ", ".join(f'"{a}"' for a in e["args"]) + "]")
        lines.append("")
    return "\n".join(lines) + "\n"


def gen_antigravity() -> str:
    servers = {}
    for name, spec in MANIFEST["mcpServers"].items():
        e = server_for_runtime(name, spec, "antigravity")
        if e:
            servers[name] = e if e.get("type") != "http" else {"serverUrl": e["url"]}
    return json.dumps({"mcpServers": servers}, indent=2) + "\n"


def apply_user(snippet_json: str, target: Path) -> None:
    target = target.expanduser()
    snippet = json.loads(snippet_json)["mcpServers"]
    existing = {}
    if target.exists():
        backup = target.with_suffix(target.suffix + f".bak-{datetime.date.today().isoformat()}")
        shutil.copy2(target, backup)
        print(f"backup: {backup}")
        existing = json.loads(target.read_text(encoding="utf-8"))
    existing.setdefault("mcpServers", {}).update(snippet)
    out = json.dumps(existing, indent=2) + "\n"
    scan(out, str(target))
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(out, encoding="utf-8")
    print(f"merged {len(snippet)} servers -> {target}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply-user", action="store_true", help="merge snippets into user configs (with backup)")
    args = ap.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    claude = gen_claude()
    codex = gen_codex()
    anti = gen_antigravity()
    for label, text in (("claude", claude), ("codex", codex), ("antigravity", anti)):
        scan(text, label)

    (ROOT / ".mcp.json").write_text(claude, encoding="utf-8")
    (OUT / "codex-mcp.toml").write_text(codex, encoding="utf-8")
    (OUT / "antigravity-mcp.json").write_text(anti, encoding="utf-8")
    print("wrote .mcp.json, harness/out/codex-mcp.toml, harness/out/antigravity-mcp.json")

    if args.apply_user:
        apply_user(anti, Path(MANIFEST["outputs"]["antigravity"]["mcpConfig"]["path"]))
        print("codex: TOML merge is manual — append harness/out/codex-mcp.toml sections to ~/.codex/config.toml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
